run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - bodyclose

linters-settings:
  errcheck:
    check-type-assertions: true

issues:
  exclude-use-default: false
